In [227]:
import pandas as pd
import numpy as np

# Data is imported from the real database
product_dataset = pd.read_csv('/content/Product_Dataset.csv')

In [230]:
product_dataset.head()
# product_dataset.shape
# product_dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 264 entries, 0 to 263
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Id                 264 non-null    int64
 1   CategoryName       264 non-null    object
 2   ProductName        264 non-null    object
 3   Price              264 non-null    int64
 4   Discount           264 non-null    int64
 5   StockQuantity      264 non-null    int64
 6   StockSold          264 non-null    int64
 7   Description        264 non-null    object
 8   DeliveryStatus     264 non-null    object
 9   ProductRating      263 non-null    float64
 10  TotalProductRated  263 non-null    float64
 11  PhotoPath          264 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 24.9+ KB

In [213]:
new_product_dataset=product_dataset[['Id','CategoryName','ProductName','Description']]
new_product_dataset.head()

,Id,CategoryName,ProductName,Description
0,6,Mobile,iPhone 15 Pro Max 256GB,### iPhone 15 Pro Max Experience the ultimate...
1,7,Mobile,Samsung Galaxy S24 Ultra,### Samsung Galaxy S24 Ultra AI-powered featu...
2,8,Mobile,OnePlus 12 5G,### OnePlus 12 5G Smooth beyond belief with S...
3,48,Mobile,Google Pixel 8 Pro,### Google Pixel 8 Pro Incredible AI camera f...
4,49,Mobile,Nothing Phone (2),### Nothing Phone (2) Unique transparent desi...

In [214]:
new_product_dataset.dropna(inplace=True)
new_product_dataset.isnull().sum()

/tmp/ipykernel_526/1278448032.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_product_dataset.dropna(inplace=True)

Id              0
CategoryName    0
ProductName     0
Description     0
dtype: int64

In [215]:
new_product_dataset.duplicated().sum()

np.int64(0)

To remove special characters

In [216]:
new_product_dataset['Description'] = new_product_dataset['Description'].str.replace(r'[^\w\s]', '', regex=True)
new_product_dataset['CategoryName'] = new_product_dataset['CategoryName'].str.replace(r'[^\w\s]', '', regex=True)
new_product_dataset['ProductName'] = new_product_dataset['ProductName'].str.replace(r'[^\w\s]', '', regex=True)

/tmp/ipykernel_526/2660895834.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_product_dataset['Description'] = new_product_dataset['Description'].str.replace(r'[^\w\s]', '', regex=True)
/tmp/ipykernel_526/2660895834.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_product_dataset['CategoryName'] = new_product_dataset['CategoryName'].str.replace(r'[^\w\s]', '', regex=True)
/tmp/ipykernel_526/2660895834.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_product_dataset['ProductName'] = new_product_dataset['ProductName'].str.replace(r'[^\w\s]', '', regex=True)

In [217]:
new_product_dataset['Description'].head().tolist()

[' iPhone 15 Pro Max  Experience the ultimate Apple flagship with titanium design',
 ' Samsung Galaxy S24 Ultra  AIpowered features and a brilliant flat display',
 ' OnePlus 12 5G  Smooth beyond belief with Snapdragon 8 Gen 3',
 ' Google Pixel 8 Pro  Incredible AI camera features and stock Android',
 ' Nothing Phone 2  Unique transparent design with Glyph interface']

Removed spaces from category name and product name

In [218]:
new_product_dataset['CategoryName'] = new_product_dataset['CategoryName'].str.replace(' ', '', regex=False)
new_product_dataset['ProductName'] = new_product_dataset['ProductName'].str.replace(' ', '', regex=False)

/tmp/ipykernel_526/2734533116.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_product_dataset['CategoryName'] = new_product_dataset['CategoryName'].str.replace(' ', '', regex=False)
/tmp/ipykernel_526/2734533116.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_product_dataset['ProductName'] = new_product_dataset['ProductName'].str.replace(' ', '', regex=False)

Combined category name, product name and description to make tags

In [219]:
new_product_dataset['tags'] = new_product_dataset['CategoryName'] + " " + new_product_dataset['ProductName'] + " " + new_product_dataset['Description']
# new_product_dataset.head()

/tmp/ipykernel_526/870934801.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_product_dataset['tags'] = new_product_dataset['CategoryName'] + " " + new_product_dataset['ProductName'] + " " + new_product_dataset['Description']

Make new dataset with necessary cleaned columns

In [231]:
final_dataset = new_product_dataset[['Id', 'tags']].copy()
final_dataset.head()

   Id                                               tags
0   6  Mobile iPhone15ProMax256GB  iPhone 15 Pro Max ...
1   7  Mobile SamsungGalaxyS24Ultra  Samsung Galaxy S...
2   8  Mobile OnePlus125G  OnePlus 12 5G  Smooth beyo...
3  48  Mobile GooglePixel8Pro  Google Pixel 8 Pro  In...
4  49  Mobile NothingPhone2  Nothing Phone 2  Unique ...

Changed tags letters to lowercase

In [221]:
final_dataset['tags'] = final_dataset['tags'].apply(lambda x: x.lower())
final_dataset.head()

/tmp/ipykernel_526/1306197513.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_dataset['tags'] = final_dataset['tags'].apply(lambda x: x.lower())

   Id                                               tags
0   6  mobile iphone15promax256gb  iphone 15 pro max ...
1   7  mobile samsunggalaxys24ultra  samsung galaxy s...
2   8  mobile oneplus125g  oneplus 12 5g  smooth beyo...
3  48  mobile googlepixel8pro  google pixel 8 pro  in...
4  49  mobile nothingphone2  nothing phone 2  unique ...

Reduced words to their root base form (e.g., 'connecting' and 'connected' both become 'connect')

In [222]:
import nltk

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
    y = []

    for i in text.split():
        y.append(ps.stem(i))

    return " ".join(y)

final_dataset['tags']=final_dataset['tags'].apply(stem)
final_dataset.head()

/tmp/ipykernel_526/4071820644.py:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_dataset['tags']=final_dataset['tags'].apply(stem)

   Id                                               tags
0   6  mobil iphone15promax256gb iphon 15 pro max exp...
1   7  mobil samsunggalaxys24ultra samsung galaxi s24...
2   8  mobil oneplus125g oneplu 12 5g smooth beyond b...
3  48  mobil googlepixel8pro googl pixel 8 pro incred...
4  49  mobil nothingphone2 noth phone 2 uniqu transpa...

We ignore filler words (like 'the' or 'and') and only keep the top 5,000 most important words.

In [223]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

vectors=cv.fit_transform(final_dataset['tags']).toarray()
print(vectors.shape)

(264, 1607)

Compare every product against every other product to calculate a "match score" (from 0 to 1) based on how many words they share in common.

In [224]:
from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)
print(similarity.shape)

(264, 264)

Loop through every product, find its top 5 closest matches based on the similarity scores,
and save the results into a lightweight JSON file for the backend to use.

In [225]:
import json

recommendations_dict = {}

for index in range(final_dataset.shape[0]):

    current_product_id = str(final_dataset.iloc[index]['Id'])

    similarity_scores = similarity[index]

    top_5_matches = sorted(list(enumerate(similarity_scores)), reverse=True, key=lambda x: x[1])[1:6]

    recommended_ids = []
    for match in top_5_matches:
        matched_index = match[0]
        matched_id = int(final_dataset.iloc[matched_index]['Id'])
        recommended_ids.append(matched_id)

    recommendations_dict[current_product_id] = recommended_ids

with open('precomputed_recommendations.json', 'w') as json_file:
    json.dump(recommendations_dict, json_file, indent=4)

print("precomputed_recommendations.json created successfully!")

precomputed_recommendations.json created successfully!

Loaded the generated JSON file and run a quick test.
This simulates exactly what our backend will do: look up an ID, instantly get the 5 matching IDs, and fetch their names to display.

In [226]:
import json

with open('precomputed_recommendations.json', 'r') as file:
    loaded_recommendations = json.load(file)

def test_recommendation_with_names(product_id):
    product_id_str = str(product_id)

    if product_id_str in loaded_recommendations:

        original_product = new_product_dataset[new_product_dataset['Id'] == product_id]
        original_name = original_product['ProductName'].values[0]

        print(f"Success! Top 5 recommendations for '{original_name}' (ID: {product_id}):\n")

        recommended_ids = loaded_recommendations[product_id_str]

        for rank, rec_id in enumerate(recommended_ids, start=1):

            matched_row = new_product_dataset[new_product_dataset['Id'] == rec_id]

            matched_name = matched_row['ProductName'].values[0]

            print(f"{rank}. ID: {rec_id} | Name: {matched_name}")

    else:
        print(f"Error: Product ID '{product_id}' not found in the JSON file.")

test_id = 235
test_recommendation_with_names(test_id)

Success! Top 5 recommendations for 'MoroccanoilTreatmentOriginal' (ID: 235):

1. ID: 200 | Name: OlaplexNo7BondingOil
2. ID: 230 | Name: ChanelNo5EaudeParfum
3. ID: 226 | Name: CetaphilGentleSkinCleanser
4. ID: 228 | Name: TarteShapeTapeContourConcealer
5. ID: 233 | Name: UrbanDecayAllNighterSettingSpray